# build.yaml file for designing the build system

init:
  compiler: g++
  object: -c -Wall
  verbose: on
  include: Core
  library: glfw3.lib

build:
  objects:
    test.obj: test.cpp
    test2.obj: test2.cpp
  link:
    test.exe: test.obj